name: web-chat
services:
  db:
    container_name: postgres-db
    environment:
      POSTGRES_DB: webchat
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15
    networks:
      - web-chat-network
    ports:
      - mode: ingress
        target: 5432
        published: "52432"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume: {}
  prometheus:
    image: prom/prometheus:latest
    container_name: web-chat-prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-chat-network
  grafana:
    container_name: web-chat-grafana
    image: grafana/grafana:latest
    ports:
      - "3065:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - db
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - web-chat-network

networks:
  web-chat-network:
    name: web-chat-network
    driver: bridge
volumes:
  postgres-data:
    name: web-chat_postgres-data
  grafana-data:
    name: web-chat_grafana-data