name: web-chat
services:
  db:
    container_name: postgres-db
    environment:
      POSTGRES_DB: webchat
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15
    networks:
      postgres-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "52432"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  postgres-network:
    name: web-chat_postgres-network
    driver: bridge
volumes:
  postgres-data:
    name: web-chat_postgres-data
