{
 "title": "WEB-CHAT",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Usage After GC",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by(area, pool) (jvm_memory_usage_after_gc)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Memory Used (Heap and Non-Heap)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "group by(area, id) (jvm_memory_used_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Memory Max Capacity",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "group by(area, id) (jvm_memory_max_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Loaded Classes",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_classes_loaded_classes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HikariCP Connections Min and Max",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by(pool) (hikaricp_connections_min)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(pool) (hikaricp_connections_max)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JDBC Idle Connections",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "group by(name) (jdbc_connections_idle)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "group by(method, status, uri) (http_server_requests_seconds_count)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group by(method, status, uri) (http_server_requests_seconds_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Request Max Time",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "group by(method, uri) (http_server_requests_seconds_max)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": " Spring Security Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorization and Authentication Metrics",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "spring_security_authorizations_active_seconds_max",
       "legendFormat": "__auto"
      },
      {
       "expr": "spring_security_filterchains_authorization_before_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filter Chains and Sessions",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "spring_security_filterchains_active_seconds_max",
       "legendFormat": "__auto"
      },
      {
       "expr": "spring_security_filterchains_session_urlencoding_before_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Session Monitoring Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}